"""initial_schema

Revision ID: 4fc5c474fb17
Revises: 
Create Date: 2025-12-16 11:44:37.733514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc5c474fb17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('GOOGLE_NEWS', 'HACKERNEWS', name='source'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentimentlabel'), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('ingested_date', sa.DateTime(), nullable=False),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_mentions_brand_id'), 'mentions', ['brand_id'], unique=False)
    op.create_index(op.f('ix_mentions_ingested_date'), 'mentions', ['ingested_date'], unique=False)
    op.create_index(op.f('ix_mentions_published_date'), 'mentions', ['published_date'], unique=False)
    op.create_index(op.f('ix_mentions_source'), 'mentions', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentions_source'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_published_date'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_ingested_date'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_brand_id'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
